// Preload lazy route chunks when hovering sidebar items.
// These must match the lazy() imports in App.tsx.
export const prefetchRoutes: Record<string, () => void> = {
  "/organization": () => { void import("@/pages/Organization"); },
  "/security": () => { void import("@/pages/Security"); },
  "/analytics": () => { void import("@/pages/Analytics"); },
  "/reports": () => { void import("@/pages/Reports"); },
  "/goals": () => { void import("@/pages/Goals"); },
  "/notifications": () => { void import("@/pages/Notifications"); },
  "/api": () => { void import("@/pages/Api"); },
  "/ai-api-settings": () => { void import("@/pages/AIApiSettings"); },
  "/audit": () => { void import("@/pages/Audit"); },
  "/support": () => { void import("@/pages/Support"); },
  "/profile": () => { void import("@/pages/Profile"); },
  "/settings": () => { void import("@/pages/Settings"); },
  "/assistant": () => { void import("@/pages/Assistant"); },
  "/finance": () => { void import("@/pages/Finance"); },
  "/inventory": () => { void import("@/pages/Inventory"); },
  "/projects": () => { void import("@/pages/Projects"); },
  "/employees": () => { void import("@/pages/Employees"); },
  "/workflows": () => { void import("@/pages/Workflows"); },
  "/custom-fields": () => { void import("@/pages/CustomFields"); },
  "/communications": () => { void import("@/pages/Communications"); },
  "/calendar": () => { void import("@/pages/Calendar"); },
  "/forecasts": () => { void import("@/pages/Forecasts"); },
  "/timesheets": () => { void import("@/pages/Timesheets"); },
  "/quotes": () => { void import("@/pages/Quotes"); },
  "/email-templates": () => { void import("@/pages/EmailTemplates"); },
  "/documents": () => { void import("@/pages/Documents"); },
  "/subscriptions": () => { void import("@/pages/Subscriptions"); },
  "/campaigns": () => { void import("@/pages/Campaigns"); },
  "/staff-directory": () => { void import("@/pages/StaffDirectory"); },
};
