// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dtrwtbmxvscrfkzdpsqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cnd0Ym14dnNjcmZremRwc3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMDY5NTgsImV4cCI6MjA5MzU4Mjk1OH0.VfQiPNBOVQBCd8AGQEgmBMNrU6RgSNHhAtjx80qborE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);